import { db } from '@/db';
import { reviews } from '@/db/schema';

async function main() {
    const sampleReviews = [
        {
            staffMemberId: 1,
            rating: 5,
            comment: 'Excellent service! Sarah was very attentive and made our dining experience memorable.',
            tipId: 1,
            approved: true,
            approvedBy: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-01-15T18:30:00').getTime(),
        },
        {
            staffMemberId: 2,
            rating: 4,
            comment: 'Great food and friendly service. Michael was professional and helpful.',
            tipId: 2,
            approved: true,
            approvedBy: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-01-16T19:15:00').getTime(),
        },
        {
            staffMemberId: 3,
            rating: 5,
            comment: 'Outstanding chef! The pasta was perfectly cooked and delicious.',
            tipId: 3,
            approved: true,
            approvedBy: 'user_02h5lyu3f9a0z4c2o8n7r6x9s5',
            createdAt: new Date('2024-01-17T20:45:00').getTime(),
        },
        {
            staffMemberId: 1,
            rating: 4,
            comment: 'Good service, though a bit slow during peak hours.',
            tipId: 4,
            approved: true,
            approvedBy: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-01-18T17:20:00').getTime(),
        },
        {
            staffMemberId: 4,
            rating: 5,
            comment: 'Emma greeted us warmly and made us feel welcome from the moment we arrived.',
            tipId: 5,
            approved: true,
            approvedBy: 'user_03h6mzv4g0b1a5d3p9o8s7y0t6',
            createdAt: new Date('2024-01-19T18:00:00').getTime(),
        },
        {
            staffMemberId: 2,
            rating: 3,
            comment: 'Service was okay but could be more attentive to customer needs.',
            tipId: null,
            approved: false,
            approvedBy: null,
            createdAt: new Date('2024-01-20T19:30:00').getTime(),
        },
        {
            staffMemberId: 5,
            rating: 5,
            comment: 'Amazing manager! David handled our special request perfectly.',
            tipId: 6,
            approved: true,
            approvedBy: 'user_02h5lyu3f9a0z4c2o8n7r6x9s5',
            createdAt: new Date('2024-01-21T20:10:00').getTime(),
        },
        {
            staffMemberId: 3,
            rating: 4,
            comment: 'Delicious food and great presentation. Will definitely come back!',
            tipId: 7,
            approved: true,
            approvedBy: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-01-22T18:45:00').getTime(),
        },
        {
            staffMemberId: 1,
            rating: 5,
            comment: 'Sarah went above and beyond to accommodate our dietary restrictions.',
            tipId: 8,
            approved: true,
            approvedBy: 'user_04h7naw5h1c2b6e4q0p9t8z1u7',
            createdAt: new Date('2024-01-23T19:00:00').getTime(),
        },
        {
            staffMemberId: 6,
            rating: 4,
            comment: 'Nice ambiance and good service. The host was very professional.',
            tipId: 9,
            approved: true,
            approvedBy: 'user_03h6mzv4g0b1a5d3p9o8s7y0t6',
            createdAt: new Date('2024-01-24T17:30:00').getTime(),
        },
        {
            staffMemberId: 2,
            rating: 2,
            comment: 'Food took too long to arrive and was cold when served.',
            tipId: null,
            approved: false,
            approvedBy: null,
            createdAt: new Date('2024-01-25T20:00:00').getTime(),
        },
        {
            staffMemberId: 4,
            rating: 5,
            comment: 'Exceptional hospitality! Emma made our anniversary dinner special.',
            tipId: 10,
            approved: true,
            approvedBy: 'user_02h5lyu3f9a0z4c2o8n7r6x9s5',
            createdAt: new Date('2024-01-26T21:15:00').getTime(),
        },
        {
            staffMemberId: 7,
            rating: 4,
            comment: 'Great server! Very knowledgeable about the menu and wine pairings.',
            tipId: 11,
            approved: true,
            approvedBy: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-01-27T18:20:00').getTime(),
        },
        {
            staffMemberId: 3,
            rating: 5,
            comment: 'Best meal we have had in months! The chef is truly talented.',
            tipId: 12,
            approved: true,
            approvedBy: 'user_05h8obx6i2d3c7f5r1q0u9a2v8',
            createdAt: new Date('2024-01-28T19:45:00').getTime(),
        },
        {
            staffMemberId: 5,
            rating: 4,
            comment: 'David handled our large group reservation perfectly. Great management!',
            tipId: 13,
            approved: true,
            approvedBy: 'user_04h7naw5h1c2b6e4q0p9t8z1u7',
            createdAt: new Date('2024-01-29T20:30:00').getTime(),
        },
        {
            staffMemberId: 1,
            rating: 3,
            comment: 'Service was good but the food was not as expected.',
            tipId: null,
            approved: false,
            approvedBy: null,
            createdAt: new Date('2024-01-30T17:15:00').getTime(),
        },
        {
            staffMemberId: 8,
            rating: 5,
            comment: 'Outstanding service from start to finish. Highly recommend!',
            tipId: 14,
            approved: true,
            approvedBy: 'user_03h6mzv4g0b1a5d3p9o8s7y0t6',
            createdAt: new Date('2024-02-01T18:50:00').getTime(),
        },
        {
            staffMemberId: 2,
            rating: 4,
            comment: 'Michael was very helpful with menu recommendations. Great experience!',
            tipId: 15,
            approved: true,
            approvedBy: 'user_02h5lyu3f9a0z4c2o8n7r6x9s5',
            createdAt: new Date('2024-02-02T19:20:00').getTime(),
        },
        {
            staffMemberId: 6,
            rating: 5,
            comment: 'Perfect evening! The host made sure everything was exactly as we wanted.',
            tipId: 16,
            approved: true,
            approvedBy: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-02-03T20:40:00').getTime(),
        },
        {
            staffMemberId: 9,
            rating: 4,
            comment: 'Solid performance all around. Will return with friends soon.',
            tipId: 17,
            approved: true,
            approvedBy: 'user_06h9pcv7j3e4d8g6s2r1v0b3w9',
            createdAt: new Date('2024-02-04T18:25:00').getTime(),
        }
    ];

    await db.insert(reviews).values(sampleReviews);
    
    console.log('✅ Reviews seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});