import { db } from '@/db';
import { tips } from '@/db/schema';

async function main() {
    const sampleTips = [
        {
            staffMemberId: 1,
            amountCents: 5000,
            currency: 'INR',
            payerName: 'Rajesh Kumar',
            message: 'Excellent service! Food was amazing.',
            source: 'qr',
            status: 'succeeded',
            createdAt: new Date('2024-01-15T10:30:00Z').getTime(),
        },
        {
            staffMemberId: 2,
            amountCents: 2000,
            currency: 'INR',
            payerName: 'Priya Sharma',
            message: 'Very attentive staff, thank you!',
            source: 'qr',
            status: 'succeeded',
            createdAt: new Date('2024-01-15T12:45:00Z').getTime(),
        },
        {
            staffMemberId: 1,
            amountCents: 3000,
            currency: 'INR',
            payerName: 'Amit Singh',
            message: 'Great recommendations on the menu.',
            source: 'link',
            status: 'succeeded',
            createdAt: new Date('2024-01-16T14:20:00Z').getTime(),
        },
        {
            staffMemberId: 3,
            amountCents: 7500,
            currency: 'INR',
            payerName: 'Sarah Johnson',
            message: 'Outstanding hospitality and delicious food!',
            source: 'qr',
            status: 'succeeded',
            createdAt: new Date('2024-01-16T18:15:00Z').getTime(),
        },
        {
            staffMemberId: 2,
            amountCents: 1500,
            currency: 'INR',
            payerName: 'Vikram Patel',
            message: null,
            source: 'qr',
            status: 'succeeded',
            createdAt: new Date('2024-01-17T11:30:00Z').getTime(),
        },
        {
            staffMemberId: 1,
            amountCents: 4000,
            currency: 'INR',
            payerName: 'Meera Gupta',
            message: 'Loved the presentation and taste!',
            source: 'pos',
            status: 'succeeded',
            createdAt: new Date('2024-01-17T13:45:00Z').getTime(),
        },
        {
            staffMemberId: 3,
            amountCents: 2500,
            currency: 'INR',
            payerName: 'David Chen',
            message: 'Quick service, very professional.',
            source: 'qr',
            status: 'pending',
            createdAt: new Date('2024-01-18T16:20:00Z').getTime(),
        },
        {
            staffMemberId: 2,
            amountCents: 6000,
            currency: 'INR',
            payerName: 'Anita Reddy',
            message: 'Best dining experience in the city!',
            source: 'link',
            status: 'succeeded',
            createdAt: new Date('2024-01-18T19:30:00Z').getTime(),
        },
        {
            staffMemberId: 1,
            amountCents: 3500,
            currency: 'INR',
            payerName: 'Ravi Agarwal',
            message: 'Helped us choose the perfect wine pairing.',
            source: 'qr',
            status: 'succeeded',
            createdAt: new Date('2024-01-19T12:15:00Z').getTime(),
        },
        {
            staffMemberId: 3,
            amountCents: 1000,
            currency: 'INR',
            payerName: 'Lisa Wong',
            message: 'Small token of appreciation.',
            source: 'qr',
            status: 'succeeded',
            createdAt: new Date('2024-01-19T15:40:00Z').getTime(),
        },
        {
            staffMemberId: 2,
            amountCents: 8000,
            currency: 'INR',
            payerName: 'Karthik Nair',
            message: 'Exceptional service for our anniversary dinner!',
            source: 'pos',
            status: 'succeeded',
            createdAt: new Date('2024-01-20T20:30:00Z').getTime(),
        },
        {
            staffMemberId: 1,
            amountCents: 2200,
            currency: 'INR',
            payerName: 'Neha Joshi',
            message: 'Very friendly and accommodating staff.',
            source: 'qr',
            status: 'succeeded',
            createdAt: new Date('2024-01-21T13:25:00Z').getTime(),
        },
        {
            staffMemberId: 3,
            amountCents: 4500,
            currency: 'INR',
            payerName: 'Michael Brown',
            message: 'Great job handling our large group!',
            source: 'link',
            status: 'succeeded',
            createdAt: new Date('2024-01-21T17:50:00Z').getTime(),
        },
        {
            staffMemberId: 2,
            amountCents: 1800,
            currency: 'INR',
            payerName: 'Deepika Rao',
            message: null,
            source: 'qr',
            status: 'failed',
            createdAt: new Date('2024-01-22T14:10:00Z').getTime(),
        },
        {
            staffMemberId: 1,
            amountCents: 5500,
            currency: 'INR',
            payerName: 'Suresh Menon',
            message: 'Outstanding knowledge of the menu items.',
            source: 'qr',
            status: 'succeeded',
            createdAt: new Date('2024-01-22T19:45:00Z').getTime(),
        },
        {
            staffMemberId: 3,
            amountCents: 3200,
            currency: 'INR',
            payerName: 'Jennifer Davis',
            message: 'Made our visit truly special.',
            source: 'pos',
            status: 'succeeded',
            createdAt: new Date('2024-01-23T12:35:00Z').getTime(),
        },
        {
            staffMemberId: 2,
            amountCents: 2700,
            currency: 'INR',
            payerName: 'Arjun Kapoor',
            message: 'Prompt service despite busy evening.',
            source: 'qr',
            status: 'succeeded',
            createdAt: new Date('2024-01-23T21:15:00Z').getTime(),
        },
        {
            staffMemberId: 1,
            amountCents: 4200,
            currency: 'INR',
            payerName: 'Shweta Iyer',
            message: 'Perfectly timed courses, excellent coordination.',
            source: 'link',
            status: 'succeeded',
            createdAt: new Date('2024-01-24T16:20:00Z').getTime(),
        },
        {
            staffMemberId: 3,
            amountCents: 6500,
            currency: 'INR',
            payerName: 'Robert Wilson',
            message: 'Went above and beyond for dietary restrictions.',
            source: 'qr',
            status: 'succeeded',
            createdAt: new Date('2024-01-24T18:55:00Z').getTime(),
        },
        {
            staffMemberId: 2,
            amountCents: 3800,
            currency: 'INR',
            payerName: 'Kavya Pillai',
            message: 'Always smiling and very helpful.',
            source: 'qr',
            status: 'succeeded',
            createdAt: new Date('2024-01-25T11:40:00Z').getTime(),
        },
        {
            staffMemberId: 1,
            amountCents: 2900,
            currency: 'INR',
            payerName: 'Harsh Agrawal',
            message: 'Great suggestions for first-time visitors.',
            source: 'pos',
            status: 'pending',
            createdAt: new Date('2024-01-25T14:30:00Z').getTime(),
        },
        {
            staffMemberId: 3,
            amountCents: 5200,
            currency: 'INR',
            payerName: 'Emily Taylor',
            message: 'Made our business lunch seamless.',
            source: 'link',
            status: 'succeeded',
            createdAt: new Date('2024-01-26T13:15:00Z').getTime(),
        },
        {
            staffMemberId: 2,
            amountCents: 1600,
            currency: 'INR',
            payerName: 'Manoj Kumar',
            message: 'Quick and efficient service.',
            source: 'qr',
            status: 'succeeded',
            createdAt: new Date('2024-01-26T20:25:00Z').getTime(),
        },
        {
            staffMemberId: 1,
            amountCents: 7000,
            currency: 'INR',
            payerName: 'Ritika Sethi',
            message: 'Perfect service for our celebration!',
            source: 'qr',
            status: 'succeeded',
            createdAt: new Date('2024-01-27T19:10:00Z').getTime(),
        },
        {
            staffMemberId: 3,
            amountCents: 4800,
            currency: 'INR',
            payerName: 'James Anderson',
            message: 'Professional and courteous throughout.',
            source: 'pos',
            status: 'succeeded',
            createdAt: new Date('2024-01-27T22:30:00Z').getTime(),
        }
    ];

    await db.insert(tips).values(sampleTips);
    
    console.log('✅ Tips seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});